{% set name = "opentelemetry-instrumentation-django" %}
{% set version = "0.28b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-django-{{ version }}.tar.gz
  sha256: e818db83e7544f8627488d347a49b5974057c9cc703c5b2c889798f9573aeccb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.28b1
    - opentelemetry-instrumentation-wsgi ==0.28b1
    - opentelemetry-semantic-conventions ==0.28b1
    - opentelemetry-util-http ==0.28b1
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-instrumentation-asgi ==0.26b1
    # - django >=1.10
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-instrumentation-asgi ==0.27b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.28b0
    # - opentelemetry-instrumentation-asgi ==0.28b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.28b1
    # - opentelemetry-instrumentation-asgi ==0.28b1
    # - django >=1.10

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-django
  summary: OpenTelemetry Instrumentation for Django
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
